name: Hello World workflow

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello World
        run: echo "Hello World" && sleep 30
      - name: print hello New Era Solution    
        run:  print "Hello New Era Solutions" && sleep 30
